#!/bin/bash -ve

#ARCHIVE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/../repo
ARCHIVE="/packaging/kern/packaging/repo"

pushd ${ARCHIVE}
apt-ftparchive packages . > Packages
apt-get update
popd
